on:
  workflow_call:
    secrets:
      RENDER_FRONTEND_HOOK:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Frontend Deploy
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_HOOK }}
