on:
  workflow_call:
    secrets:
      RENDER_BACKEND_HOOK:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Backend Deploy
        run: curl -X POST ${{ secrets.RENDER_BACKEND_HOOK }}
